// Creates a function that returns a license badge based on which license is passed in
// If there is no license, returns an empty string
function renderLicenseBadge(license) {
  const licenseKey = [
    ['Apache License 2.0', 'Apache_2.0-blue'],
    ['GNU general Public License v3.0', 'GPLv3-blue'],
    ['MIT license', 'MIT-yellow'],
    ['BSD2-Clause "Simplified" License', 'BSD_2--Clause-orange'],
    ['BSD 3-Clause "New" or "Revised" License', 'BSD_3--Clause-blue'],
    ['Boost Software License 1.0', 'Boost_1.0-lightblue'],
    ['Eclipse Public License 2.0', 'EPL_2.0-red'],
    ['GNU General Public License v2.0', 'GPL_v2-blue']
  ]
  if (license !== 'None') {
    for (let i = 0; i < licenseKey.length; i++) {
      if (licenseKey[i][0] === license) {
        return licenseKey[i][1]      
      }
    }
  } 
  return '';
  }

// Creates a function that returns the license link
// If there is no license, returns an empty string
function renderLicenseLink(license) {
  if (license !== 'None') {
    licenseLiteral = renderLicenseBadge(license)
    let licenseLink = `![GitHub license](https://img.shields.io/badge/license-${licenseLiteral}.svg)`
    return licenseLink;
  }
  return '';
  }

// Creates a function to generate markdown for README
function generateMarkdown(data) {
  let license = data.license
  let markdown = renderLicenseLink(license)
  let markdownTemplate = `
# ${data.title}
    
## Description
    
${data.description}
  
## Table of Contents

- [Installation](#installation)
- [Usage](#usage)
- [Contributing](#contributing)
- [Tests](#tests) 
- [Questions](#questions)
- [Credits](#credits)
- [License](#license)
  
## Installation
${data.installation}
  
  
## Usage
${data.usage}

## Contributing
${data.contribution}

## Tests
${data.testInstruc}

## Questions
For any questions, contact me by email or on Github. Relevant links are listed below:

[Contact my GitHub account](https://github.com/${data.githubUser})

email me at: ${data.email}

## Credits
This application was generated by Nathan Moon.

## license

this application is licensed under ${data.license}. For more information about this license, please visit:

[Choosealicense.com](https://choosealicense.com/appendix/)

`
  markdown += markdownTemplate
  return markdown
}

// exports modules for use in index.js
module.exports = {
  generateMarkdown
}